name: Push/PR pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  TAG: "v0.0.0" 
  REPO_FULL_NAME: ${{ github.event.repository.full_name }}
  ORIGINAL_REPO_NAME: "newrelic/nri-oracledb"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  GO_VERSION: '1.9.7'

jobs:

  validate:
    name: Validate code via linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate code
        run: make ci/validate

  test-nix:
    name: Run unit tests on *Nix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: make ci/test

  build:
    name: Build binary for all platforms:arch
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build all platforms:arch
        run: make ci/build

  snyk:
    name: Run security checks via snyk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{env.SNYK_TOKEN}}
        with:
          args: --severity-threshold=high

